"""Dashboard tools router for engineering briefings and analytics."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app.models import (
    DailyEngineeringBriefingRequest,
    DailyEngineeringBriefingResponse,
)
from app.services import dashboard_tools as dashboard_tools_service
from app.services.logging_utils import get_logger

router = APIRouter(prefix="/tools/dashboard", tags=["dashboard"])
logger = get_logger(__name__)


@router.post(
    "/daily-engineering",
    response_model=DailyEngineeringBriefingResponse,
)
async def create_daily_engineering_briefing(
    request: DailyEngineeringBriefingRequest,
) -> DailyEngineeringBriefingResponse:
    """
    Generate a daily engineering briefing.

    Collects:
    - Recent commits (last 24h) from local git repository
    - Open PR branches (feature/*, fix/*)
    - Key changes in backend/app and ops/scripts
    - FoKS/FBP/LM Studio health status
    - Optional Obsidian notes

    Returns a markdown-formatted briefing generated by LM Studio.
    Falls back to template-based markdown if LM Studio is unavailable.

    Args:
        request: Briefing request with optional repo path, Obsidian path,
            and FBP health flag

    Returns:
        DailyEngineeringBriefingResponse: Markdown-formatted engineering
            briefing

    Raises:
        HTTPException: If briefing generation fails completely
            (even fallback fails)
    """
    logger.info(
        "Daily engineering briefing requested",
        extra={
            "payload": {
                "repo_path": request.repo_path,
                "include_fbp_health": request.include_fbp_health,
                "has_obsidian_path": bool(request.obsidian_path),
            }
        },
    )

    try:
        result = await dashboard_tools_service.build_daily_engineering_briefing(
            repo_path=request.repo_path,
            obsidian_path=request.obsidian_path,
            include_fbp_health=request.include_fbp_health,
        )
        logger.info(
            "Daily engineering briefing generated successfully",
            extra={
                "payload": {
                    "markdown_length": len(result.get("markdown", ""))
                }
            },
        )
        return DailyEngineeringBriefingResponse(markdown=result["markdown"])
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "Failed to generate daily engineering briefing",
            exc_info=True,
            extra={
                "payload": {
                    "error_type": type(exc).__name__,
                    "error_message": str(exc),
                }
            },
        )
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate briefing: {str(exc)}",
        ) from exc
