from __future__ import annotations

from typing import Any

from app.services.logging_utils import get_logger

logger = get_logger(__name__)


class ScriptGeneratorService:
    """
    FoKS Judge Component: Generates deterministic, non-branching Bash scripts.
    This is where intent is transformed into explicit Bailiff instructions.
    """

    def generate_mode_script(self, validated_config: dict[str, Any]) -> str:
        """
        Generates a linear Bash script from the validated target state.
        Ensures strict Fail-Fast behavior with 'set -e'.
        """
        mode_name = validated_config.get("mode_name", "Unknown Mode")
        state = validated_config.get("state", {})

        lines = [
            "#!/bin/bash",
            f"# FoKS Generated - Deterministic Execution for: {mode_name}",
            "# DO NOT EDIT - This script is generated by the Control Plane.",
            "",
            "set -e # Strict Fail-Fast: Stop on any command error",
            "",
            "# 1. Folder State Initialization",
        ]

        # Add folders (open commands for macOS)
        for folder in state.get("folders", []):
            path = folder["path"]
            lines.append(f'open "{path}"')

        lines.append("")
        lines.append("# 2. Application State Initialization")

        # Add applications
        for app in state.get("applications", []):
            path = app["path"]
            lines.append(f'open -a "{path}"')

        lines.append("")
        lines.append("# 3. Final Evidence Log Request")
        lines.append('echo "Execution of {mode_name} completed successfully."')

        script = "\n".join(lines)

        logger.debug(
            f"Generated deterministic script for mode: {mode_name}",
            extra={"script_length": len(lines)},
        )

        return script


script_generator_service = ScriptGeneratorService()
